version: '3'
services:
    php-fpm:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./public:/var/www/html/public
            - ./.env:/var/www/html/.env
        image: firo.zip-php
        healthcheck:
            test: [ "CMD-SHELL", "cgi-fcgi -bind -connect localhost:9000" ]
            interval: 10s
            timeout: 5s
            retries: 5
        environment:
            - APP_DEBUG=true
            - APP_ENV=dev
            - LOG_CHANNEL=stderr
            - APP_KEY=base64:5ZO9bkxYcFN07B1m1gfnOZvmCKLtk5xRro0to=
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=password
            - APP_URL=${APP_URL}

        networks:
            - internet
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        image: nginx-server
        restart: unless-stopped
        tty: true
        ports:
            - "8000:80"
        volumes:
            - ./cache:/var/cache/nginx
            - ./public:/var/www/html/public

        depends_on:
            php-fpm:
                condition: service_healthy
        networks:
            - internet
    db:
        image: public.ecr.aws/docker/library/mysql:latest
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # (this is just an example, not intended to be a production configuration)
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: laravel
        networks:
            - internet

        ports:
            - "${DB_PORT}:3306"

    adminer:
        image: adminer
        restart: always
        ports:
            - 0:8080
        depends_on:
            - db
        command:
            [
                "php",
                "-d",
                "upload_max_filesize = 10G",
                "-d",
                "post_max_size = 10G",
                "-S",
                "[::]:8080",
                "-t",
                "/var/www/html"
            ]
        networks:
            - internet
networks:
    internet:
        driver: bridge
