version: '3'
services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: ghcr.io/ashrafakon/firo.zip/php:latest
    pull_policy: if-not-present
    healthcheck:
      test: [ "CMD-SHELL", "cgi-fcgi -bind -connect localhost:9000" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=true
      - APP_ENV=dev
      - LOG_CHANNEL=stderr
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_URL=${APP_URL}

    networks:
      - prod-net
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: nginx-server
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_PORT}:80"
    # volumes:
    #   - ./public:/var/www/html/public

    depends_on:
      php-fpm:
        condition: service_healthy
    networks:
      - prod-net
  db:
    image: public.ecr.aws/docker/library/mysql:latest
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - prod-net

    ports:
      - "${DB_PORT}:3306"

networks:
  prod-net:
    external: true

volumes:
  dbdata:
